### PR TITLE
Support for overlapping events, ability to display child components in events.

### PR DESCRIPTION
**Pull request by OffensivelyBad**
Adds eventCount and eventOrder optional props to CalendarEvent in order to apply styling to layer the events on top of each other.

Adds an optional children property to the DayJSConvertedEvent interface to render custom components on events.

Adds utility functions and unit tests.

Moves the colors to a theme file.

### CODE REVIEW

**Comment by acro5piano** [comment]
@OffensivelyBad Nice!! I'll check it out soon.

**Comment by acro5piano** [comment]
@OffensivelyBad 
Great feature. Could you add some documentation about this feature?

- `children` in Event
- notes for overlapping events colors

Thank!

**Comment by OffensivelyBad** [comment]
@acro5piano I updated the readme for `children` and overlapping event colors.  I also tweaked the colors in theme.

**Comment by acro5piano** [comment]
Thank you very much!

**Pull request merged**
