### PR TITLE
Day mode implemented

### PR DESCRIPTION
**Pull request by joelbarron**
Day mode view has been implemented

### CODE REVIEW

**Comment by acro5piano** [comment]
@joelbarron 
Thank you very much!
For confirmation and demo, could you add this feature to [storybook](https://github.com/llotheo/react-native-big-calendar/blob/master/stories/index.stories.tsx)?

**Comment by acro5piano** [comment]
@joelbarron 

I've confirmed your code works. Storybook and a little bit modification is needed, but I'll do them.
Thank you for your contribution!

**Comment by joelbarron** [comment]
Sorry i was too busy at weekend, thank you!

**Comment by acro5piano** [comment]
@joelbarron No problem. Thank you!

**Pull request merged**
